### ISSUE TITLE
Manual Cookiebot Mode

### ISSUE THREAD

**Issue by nordcomputer** [customgento/module-cookiebot-m2#19]
Just to be clear:
Do I need to add the cookie-group manually in the magento2 code for every script, that might set a cookie and/or does the scanreport give me some clues, what scripts are affected?
To search for every script that might set cookies sounds awful (I know, that is not the fault of this extention).

**Comment by sprankhub** [comment]
Both :-) If you run a scan via Cookiebot, the report you get via mail and which you can open via the backend includes references to the place, where the cookie is set (if it is set client-side). So as long as we talk about client-side cookies, you get a hint, where you need to look at. Obviously, Cookiebot cannot tell you that for server-side cookies. In this case, it only shows that the cookie is set by the server.

But yes, when you found out, which scripts set cookies, you need to implement the necessary changes yourself manually (changing the `type` to `text/plain` and setting e.g. `data-cookieconsent="marketing"`).

**Comment by nordcomputer** [comment]
thank you for the clarification - I guess, I will have to look into other solutions than cookiebot...

**Comment by sprankhub** [comment]
Feel free to do so, but may I ask why? The automatic cookie detection is great IMHO. And it is nearly impossible to do cookie auto-blocking with RequireJS. I am pretty sure no other provider correctly supports blocking cookies automatically with M2s RequireJS implementation.

**Comment by nordcomputer** [comment]
Right now, we are struggeling with our gtm-implementation, that basically loads the analytics scripts. I am tinkering around with the amasty cookie consent extention, but it has massive problems with gtm/analytics, when the page is in production mode. Is there any chance, we could have a little chat about that topic, as it would be more easy to explain it in german and I still have to figure out, what really is needed for a proper (lawful) cookie consent implementation...

**Comment by sprankhub** [comment]
My company customgento.com is open to consulting work, yes :stuck_out_tongue_winking_eye: Feel free to send a mail to simon@ and we'll see what we can do :v:

**Comment by nordcomputer** [comment]
Thank you - you`ll get my mail in my office-hours tomorrow ;-)
