### ISSUE TITLE
European CDN solution

### ISSUE THREAD

**Issue by colaholiker** [customgento/module-cookiebot-m2#22]
Guten Morgen,

wäre es möglich in den Einstellungen auch eine Einstellung für die European CDN solution hinzuzufügen.

https://support.cookiebot.com/hc/en-us/articles/4530208762396-Cookiebot-CMP-European-CDN-solution

Mfg

**Comment by sprankhub** [comment]
Yes, we'll look into it.

**Comment by sprankhub** [comment]
Released in [version 2.3.0](https://github.com/customgento/module-cookiebot-m2/releases/tag/v2.3.0).

**Comment by colaholiker** [comment]
eine kleinigkeit.
sollte in der csp_whitelist.xml auch die eu domain hinzugefügt werden?

**Comment by sprankhub** [comment]
Right! Released in [version 2.3.1](https://github.com/customgento/module-cookiebot-m2/releases/tag/v2.3.1).
